services:
  hermes-jl:
    build: .
    network_mode: bridge
    image: hermes-jl
    working_dir: /app
    hostname: "0.0.0.0"
    ports: ["3000:3000"]
    env_file: [.env.local]
    command: node server.js
    restart: unless-stopped
