on:
  push:
  workflow_dispatch:
name: 🚀 Deploy
jobs:
  web-deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🛑 Stop pm2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.USER_URL }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
          script: pm2 stop jasperlorelai.eu/main.config.js

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.USER_URL }}
          remote-user: ${{ secrets.USER_NAME }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: jasperlorelai.eu/hermes

      - name: 🟢 Start pm2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.USER_URL }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
          script: pm2 start jasperlorelai.eu/main.config.js
